name: Build and Deploy to Azure Kubernetes Service (AKS)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}  # Azure service principal's appId
        password: ${{ secrets.ACR_PASSWORD }}  # Azure service principal's password

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubernetes-cli@v1
      with:
        azure-cluster: ${{ secrets.AKS_CLUSTER_NAME }}
        azure-resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
